name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: raku -v
        run: |
          raku -v

      - name: raku -V
        run: |
          raku -V

      # temp - get Bzip2 from git
      - name: Install Dependencies
        run: |
          zef install --/test https://github.com/Altai-man/perl6-Compress-Bzip2-Raw.git
          zef install --/test https://github.com/Altai-man/perl6-Compress-Bzip2.git
          zef install --/test --deps-only --build-depends --test-depends .

      - name: Run Tests
        run: |
          zef test --debug .

      - name: Install
        run: |
          zef install --/test --debug .
